### ISSUE TITLE
couldn't follow the readme

### ISSUE THREAD

**Issue by medyagh** [afbjorklund/build-size#1]
Hi I tried to follow the readme to learn how I can use this in minikube CI
my goal is on each build we measure the build size. how could I do that on a minikube repo?

I tried folowing
WORK=$(pwd) build-size

and also 
 go get -work github.com/kubernetes/minikube

but I dont know how to use it if you please guide me

**Comment by afbjorklund** [comment]
Normally I just hack it into the Makefile (the `-work`) flag, but $WORK is not equal to $PWD.
